// Curated against this fork's sources, not a promise of a general-purpose SDK.
export const REFERENCE = [
  { title: '01 / PUBLIC AUTOMATION SURFACE', rows: [
    ['mouse move x y', '--human --duration ms --steps n --seed n', 'Integer CSS coordinates. Seeded curved path; cubic ease-out starts fast and slows into the exact target. Explicit steps: 1–240.'],
    ['click selector --human', 'selector or snapshot ref', 'Resolve element target, move to it, settle 120 ms, press/release. Recording holds the press for 67 ms.'],
    ['mouse down / mouse up', 'left button by default', 'Independent press/release; moves between them are drags. Wait explicitly for an intentional hold.'],
    ['wait ms', 'integer milliseconds', 'A deterministic pause. Use only for an intended reading hold or UI readiness, not agent deliberation.'],
    ['batch --bail', 'stdin JSON: string[][]', 'Run the complete take sequentially. Stop on error; no LLM decisions between recorded actions.'],
    ['keyboard inserttext text', 'literal text; no key events', 'Use after Enter down/up, editor settle, Select All. Replaces the initial paragraph and avoids an extra newline.'],
    ['record start path / record stop', '--fps 60 --cursor-theme path --cursor-scale 0.4', 'Native CDP capture + encoder. Pointer is painted during capture, not added in post. MP4 uses VideoToolbox on macOS.'],
    ['--cursor-icon / --cursor-hotspot', 'local SVG path / x,y in original viewBox', 'One fixed icon. --cursor-scale scales image and hotspot together. --cursor-size is an alternate target size. No OS cursor-size ceiling.'],
    ['--cursor-theme theme.json', '{default, pointer?, text?}: {icon, hotspot:[x,y]}', 'Default required. Paths relative to theme JSON. Optional semantic variants, default fallback. Cannot combine with icon/hotspot/size flags.'],
    ['Native Retina launch', '--args --force-device-scale-factor=2; set viewport 1280 800 2', 'New browser session required. 1280×800 logical → actual 2560×1600 capture; verify source JPEG dimensions.'],
  ] },
  { title: '02 / DETERMINISTIC EXAMPLE SCRIPTS', rows: [
    ['cursor-theme-demo.mjs', '--theme path --output path [--verify]; AGENT_BROWSER_BIN optional', 'Standalone local fixture. Switch cursor types, type, drag-select a sentence, drag a card into a target. One batch; actual DOM postflight checks.'],
    ['move(x, y, duration=600)', 'script-local helper; seed 42; steps ≈ duration/16.67', 'Round CSS coordinates; compile one human mouse move. selectText and dragCard are command arrays, not exported SDK functions.'],
    ['selectText / dragCard arrays', 'measured text endpoints / card and drop centers', 'Selection: approach 650, settle 120, drag 1150, hold 950 ms. Drop: approach 700, settle 160, drag 1400, hold before up 180, read 950 ms.'],
    ['cursor-theme-demo.html', '#action, #input, #auto-text, #drag-card, #drop-zone', 'Real selectable text and pointer-captured drag/drop. grab/grabbing currently fall back to default; not native HTML5 DataTransfer drag/drop.'],
    ['decode-color-grid.mjs', '--base-url --dev-user-id --username OR --board-url; --output --cursor-icon --cursor-scale --cursor-hotspot [--dry-run]', '12 labeled rectangles, 4×3 grid. Set each color, Solid once, select all, Shift+2. Local dev auth and a fresh empty board.'],
    ['buildCommands(options)', '{output, cursorIcon, cursorScale="0.5", cursorHotspot="59,28", selectAll="Meta+a"}', 'Exported grid helper returns the complete CLI command array. Dry run shows it without opening a browser.'],
    ['verifyBoard(board)', 'read-only editor snapshot', 'Exported grid assertion: 12 rectangle geos, exact one-paragraph labels/colors, inherited solid fill, middle alignment, geometry, selection and centering.'],
    ['sourceDimensions(endpoint)', 'CDP WebSocket endpoint; script-local', 'Grab one source screencast JPEG and inspect with ffprobe. Reject an upscaled low-resolution source before recording.'],
  ] },
  { title: '03 / INTERNAL CURSOR & MOTION ENGINE', rows: [
    ['human_mouse_duration_ms(distance)', 'distance in CSS px → clamp(220 + 0.45d, 260, 900) ms', 'Generous minimum for short trips. Target size is intentionally not part of the timing yet.'],
    ['interpolated_mouse_steps(...)', 'distance, duration_ms, requested_steps?, human', 'Human auto cadence ≈ 120 Hz, spatial minimum; clamp 1–240. Example scripts explicitly request ≈60 Hz.'],
    ['interpolated_mouse_point(...)', 'start, target, perpendicular, seeded bend, step/steps, human', 'Human cubic ease-out 1−(1−t)³. Bend shares the eased progress so arrival does not hook sideways. Smooth nonhuman mode uses symmetric smoothstep.'],
    ['move_mouse_interpolated(...)', 'CDP client/session, MouseState, target, timing, seed, buttons, viewport offset, shared cursor', 'One absolute schedule; awaits CDP acknowledgements. Intended durations are not hard real-time guarantees.'],
    ['resolveCursor() / refreshCursor()', 'actual input point; computed CSS + glyph hit-test', 'Explicit CSS wins. auto infers text on editable fields or glyphs, not container padding. none hides; unsupported types default; stationary check every 80 ms.'],
    ['drawPointer(x,y,opacity,blur=0)', 'DPR-aware canvas; scaled per-icon hotspot', 'Native recorder uses the accepted Soft disk preset behind the icon, smooth 0.94× pressed scale, and fixed 2.5 px blur trail. Gesture timing is unchanged.'],
    ['animate(time)', 'requestAnimationFrame timestamp', 'Elapsed-time smoothing with 13 ms time constant in free motion; exact input point during dragging. Stable canvas damage avoids cursor-only screencast stalls. Stops when idle.'],
    ['RecordingCursorStyle::from_options / from_theme', 'RecordingOptions / local JSON + SVGs', 'Validate dimensions/hotspots, resolve relative paths, preload embedded images before recording. CLI and MCP share parser semantics.'],
  ] },
  { title: '04 / ASSETS & OUTPUTS', rows: [
    ['left_ptr.svg → default', 'viewBox 200×200; hotspot [59,28]', 'Large arrow from seflless/seflless.com/public/cursors. Demo scale 0.4; original asset size, not OS pointer size.'],
    ['hand2.svg → pointer', 'viewBox 200×200; hotspot [67,30]', 'Hand for CSS pointer. Each asset keeps its own hotspot while changing shape.'],
    ['xterm.svg → text', 'viewBox 200×200; hotspot [100,104]', 'I-beam for text. Grab/grabbing/resize/move artwork still to be mapped.'],
    ['cursor-theme.example.json', 'default / pointer / text entries', 'Portable mapping, relative SVG paths. Source SVGs supplied at build time, not committed here; preserve their provenance/license when redistributing.'],
    ['Theme take sidecars', '.commands.json .result.json .verification.json .final.png', 'Commands, actual command results, selected-text/drop assertions, final still. --verify also creates diagnostic video/stills outside the take.'],
    ['Grid take sidecars', '.commands.json .commands-result.json .manifest.json .png', 'Includes source size, Chrome version, output metadata, cursor checksum/settings and verified board state. Never silently overwrite takes.'],
    ['Repeatability docs', 'examples/recordings/README.md; docs/solutions/performance-issues/cursor-stalls-native-recording-20260922.md', 'Capture recipe, pacing, Retina pitfalls, frame-stall investigation and focused validation. 60 fps metadata alone does not prove 60 distinct source frames.'],
  ] },
  { title: '05 / WORKBENCH MODEL (SOFT DISK MATCHES NATIVE DEFAULT)', rows: [
    ['humanPoint(from,to,progress,seed=42)', '{x,y}, {x,y}, 0…1, integer', 'Mirrors the Rust u64 seed mixer and geometric ease-out continuously. Does not model CDP latency, event sampling or capture stalls.'],
    ['feedbackAt(events,time,config)', 'ms; press/hold/release settings', 'Pure seekable state: {radius,opacity,scale,phase}. Press starts visible; hold static; release grows/fades. Quick up starts from the current press state.'],
    ['sample(events,time,config)', 'ordered events; time in ms', 'Adds x/y, pressed, moving, pressPoint. Movement is orthogonal to press/hold/release/up. Scrub backward without accumulated state.'],
    ['validateEvents(events)', 'move:{at,x,y,duration,seed}; down/up:{at}', 'Reject overlapping moves, invalid coordinates/times, unmatched down/up. Input coordinates are integer CSS pixels in a 720×400 scene.'],
    ['compileBatch(events)', 'validated event array → string[][]', 'Initial instant positioning; human moves with duration/steps/seed; waits for gaps; down/up; end hold. No recording setup or cursor feedback flags.'],
    ['Feedback config', 'cursor:{scale,type}; press:{duration,radius,opacity,scale}; hold:{radius,opacity,width}; release:{duration,radius}; appearance:{color,filled,hotspot}', 'Soft disk: 90 ms press, 16→30 px radius, 0.16→0.20 opacity, 0.94× cursor scale. Hold steady; release pulses to 48 px and fades over 200 ms. Filled toggles disk/outline; width affects only the outline. Both draw behind the icon.'],
    ['Preset + timeline JSON', 'version:2, scenario, viewport:[720,400], feedback, events', 'Portable download/import. Dialkit presets persist locally under a new versioned key; old ring settings remain stored separately. Nothing is uploaded or automatically applied to native recording.'],
  ] },
];
